apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - triton-gateway.yaml
  - configmaps.yaml
  - serving-manifest-configmap.yaml
  - candidate-orchestrator.yaml
  - classifier-worker.yaml
  - classification-result-writer.yaml
  - variable-star-triton.yaml
