apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: classifier-worker
  namespace: variable-star
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: classifier-worker

  minReplicaCount: 2
  maxReplicaCount: 3

  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: classifier-worker-keda-hpa
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
        scaleDown:
          stabilizationWindowSeconds: 120
          selectPolicy: Max
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60

  triggers:
    - type: prometheus
      metricType: AverageValue
      metadata:
        serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: >-
          sum(
            astro_kafka_consumer_group_lag{
              group="light-curve-classification-command-group",
              topic="light-curve-classification-command"
            }
          )
        threshold: "5"
        ignoreNullValues: "false"
        timeout: "3s"

    - type: prometheus
      metricType: Value
      metadata:
        serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        query: >-
          max(
            astro_kafka_consumer_group_oldest_uncommitted_age_seconds{
              group="light-curve-classification-command-group",
              topic="light-curve-classification-command"
            }
          ) > bool 30
        threshold: "0.5"
        ignoreNullValues: "false"
        timeout: "3s"
