apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-rules-variable-star.yaml
  - podmonitor-variable-star-applications.yaml
  - podmonitor-triton-gateway.yaml
  - triton-external-metrics.yaml

configMapGenerator:
  - name: grafana-dashboard-application-operations
    namespace: monitoring
    files:
      - application-operations.json=dashboards/application-operations.json
    options:
      labels:
        grafana_dashboard: "1"

  - name: grafana-dashboard-kafka-retry-dlq
    namespace: monitoring
    files:
      - kafka-retry-dlq.json=dashboards/kafka-retry-dlq.json
    options:
      labels:
        grafana_dashboard: "1"

  - name: grafana-dashboard-kubernetes-go-postgresql
    namespace: monitoring
    files:
      - kubernetes-go-postgresql.json=dashboards/kubernetes-go-postgresql.json
    options:
      labels:
        grafana_dashboard: "1"


  - name: grafana-dashboard-gateway-triton
    namespace: monitoring
    files:
      - gateway-triton.json=dashboards/gateway-triton.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
